# Generated by Django 3.2.8 on 2022-04-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220415_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
    ]
