# Generated by Django 3.2.8 on 2022-05-08 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_room_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated']},
        ),
    ]
